import type { Metadata } from "next";
import Navigation from "@/components/navigation";
import { ThemeProvider } from "@/components/theme-provider";

export const metadata: Metadata = {
  title: "b_box | Annotator Secondary",
  description: "Generated by create next app",
};

export default function AnnotatorLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        {/* <Navigation announce={false} /> */}
        {children}
      </ThemeProvider>
    </div>
  );
}
